export const USER="user/"
export const LOGIN=USER+"login/"
export const SIGNUP=USER+"register/"
export const ME=USER+"me/"
export const LOGOUT=USER+"logout/"
export const WORKSPACE="workspace/"
export const CREATE_WORKSPACE=WORKSPACE+"create_workspace/"
export const GET_WORKSPACE=WORKSPACE+"get_workspace/"